favicon: https://raw.githubusercontent.com/learner-lu/picbed/master/logo.png
title: Document
markdown_folder: md-docs
html_folder: docs
options:
  enable_change_mode: true
  enable_copy_code: true
  enable_highlight: true
  enable_next_front: true
  enable_navigator: true
  enable_search:
    enable: false
    search_scope: []
  enable_picture_title: false
  enable_picture_preview: true
  enable_mermaid: false
  enable_github: true
  enable_latex: false
position:
  markdown_body_left: 20%
  markdown_body_right: 20%
  dir_left: 4%
  dir_top: 6%
  dir_width: 12%
  dir_height: 90%
  button_right: 6%
  button_top: 60%
  button_width: 10%
  navigator_left: 83%
  navigator_top: 10%
  navigator_max_width: 15%
  dir_item_margin: 25px
  dir_item_margin_left: -10px
  dir_second_item_margin: 0px
  dir_second_item_margin_left: 5px
  navigator_margin: 10px
  navigator_item_margin_left: -10px
  image_preview_width: 60%
color:
  body_bg_color: '#eee'
  body_bg_color_dark: '#181c27'
  markdown_bg_color: '#fff'
  markdown_bg_color_dark: '#252D38'
  markdown_box_shadow: rgba(17, 17, 26, 0.1) 0px 4px 16px, rgba(17, 17, 26, 0.05)
    0px 8px 32px
  markdown_picture_box_shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px
  markdown_code_box_shadow: rgba(17, 17, 26, 0.1) 0px 0px 16px
  text_color: '#3c4858'
  text_color_dark: '#c4c6c9'
  hash_header_color: '#000'
  hash_header_color_dark: '#c4c6c9'
  post_link_color: '#0366d6'
  post_link_color_dark: '#1589e9'
  link_hover_color: '#30a9de'
  link_hover_color_dark: '#30a9de'
  dir_tree_color: '#000'
  dir_tree_hover_color: '#000'
  dir_second_tree_color: '#000'
  dir_second_tree_hover_color: '#000'
  picture_text_color: '#a3a1a1'
  picture_preview_bg_color: rgba(0, 0, 0, 0.3)
font:
  font_size: 16px
  font_family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif,
    Apple Color Emoji, Segoe UI Emoji
  letter_spacing: 0.02em
  dir_item_font_size: 18px
  navigator_item_font_size: 14px
  dir_second_item_font_size: 16px
